### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by lovasoa** [adamboche/python-marshmallow-union#34]
Hello, 
  I'm the maintainer of marshmallow-dataclass, which includes marshmallow-union as an optional dependency. I don't think the approach of this library (finding the correct field type by trying serialization) is fundamentally flawed, and I see several ways to improve the library. I would be ready to help with the maintenance if you want me to. @adamboche, would you be ready to accept new pull requests, or should I rather create a new project ?

**Comment by adamboche** [comment]
Hey @lovasoa, thanks for reaching out. I don't have much time to work on this at the moment, but I could add you as a committer if that would work for you?

**Comment by lovasoa** [comment]
Hello @adamboche :) Yes, that would be great :)

**Comment by adamboche** [comment]
Done. :-)

**Comment by lovasoa** [comment]
@adamboche : Could we also setup continuous deployment to PyPI ? Otherwise, I can ping you for new releases.

**Comment by adamboche** [comment]
I've added you as maintainer on PyPI.

**Comment by lovasoa** [comment]
Thank you !
