### ISSUE TITLE
Release date for v0.1.15

### ISSUE THREAD

**Issue by ammerzon** [adamboche/python-marshmallow-union#36]
Are there any specific plans when v.0.1.15 will be released? Especially [PR-33](https://github.com/adamboche/python-marshmallow-union/pull/33) would be interesting.

**Comment by lovasoa** [comment]
v0.1.15 is already on pypi: https://pypi.org/project/marshmallow-union/#history

**Comment by lovasoa** [comment]
I just updated the version number in all places that still referenced v0.1.14, tagged v0.1.15 in git, and released the changes on pypi as v0.1.15.post1
