### ISSUE TITLE
marshmellow-union on conda-forge

### ISSUE THREAD

**Issue by k-dominik** [adamboche/python-marshmallow-union#43]
Dear @adamboche (and all others who identify as owners of this wonderful package),

I would like to add `marshmallow-union` to the conda-forge package manager. There is an open PR here: https://github.com/conda-forge/staged-recipes/pull/15250

Would you be okay with that?

This doesn't mean any additional work on your side, once you publish a new version on pypi, the process is almost automatic to rebuild on conda-forge. I would gladly add you @adamboche to the recipe maintainers if you want that. But I am happy maintaining it.

Cheers
Dominik

**Comment by lovasoa** [comment]
Hello @k-dominik ! Could you add me to the maintainers as well ?

**Comment by adamboche** [comment]
@k-dominik That works for me. 

Thanks @lovasoa.

**Comment by k-dominik** [comment]
awesome - the package is available now :) thank you both, @adamboche and @lovasoa
